"""DM Automation schemas."""
from app.schemas.auth import (
    LoginRequest,
    SignupRequest,
    TokenRequest,
    TokenResponse,
    UserResponse,
    ChangePasswordRequest,
    APIKeyRequest,
    APIKeyResponse,
)
from app.schemas.instagram import (
    InstagramOAuthCallbackRequest,
    InstagramOAuthStartResponse,
    InstagramAccountResponse,
    InstagramAccountListResponse,
    SetPrimaryAccountRequest,
    DisconnectAccountRequest,
    AccountStatusResponse,
)
from app.schemas.automation import (
    CreateAutomationRequest,
    UpdateAutomationRequest,
    AutomationResponse,
    AutomationListResponse,
    TestAutomationRequest,
    TestAutomationResponse,
    TriggerSchema,
    StepSchema,
    MessageTemplateSchema,
    ButtonSchema,
    CarouselElementSchema,
)
from app.schemas.contact import (
    ContactCreateRequest,
    ContactUpdateRequest,
    ContactResponse,
    ContactListResponse,
    ContactSearchRequest,
    BulkCreateContactsRequest,
    BulkCreateContactsResponse,
    AddTagRequest,
    RemoveTagRequest,
    ContactExportRequest,
    ContactImportRequest,
    ContactImportResponse,
)
from app.schemas.message import (
    TextMessageSchema,
    GenericTemplateSchema,
    CarouselSchema,
    ImageMessageSchema,
    VideoMessageSchema,
    FileMessageSchema,
    CreateMessageTemplateRequest,
    UpdateMessageTemplateRequest,
    MessageTemplateResponse,
    MessageTemplateListResponse,
    PreviewMessageRequest,
    PreviewMessageResponse,
)
from app.schemas.analytics import (
    DailyAnalyticsResponse,
    DateRangeAnalyticsResponse,
    PerformanceMetricsResponse,
    EngagementMetricsResponse,
    ErrorBreakdownResponse,
    AnalyticsDashboardResponse,
    ExportAnalyticsRequest,
    AutomationAnalyticsResponse,
    StepAnalyticsResponse,
)

__all__ = [
    # Auth schemas
    "LoginRequest",
    "SignupRequest",
    "TokenRequest",
    "TokenResponse",
    "UserResponse",
    "ChangePasswordRequest",
    "APIKeyRequest",
    "APIKeyResponse",
    # Instagram schemas
    "InstagramOAuthCallbackRequest",
    "InstagramOAuthStartResponse",
    "InstagramAccountResponse",
    "InstagramAccountListResponse",
    "SetPrimaryAccountRequest",
    "DisconnectAccountRequest",
    "AccountStatusResponse",
    # Automation schemas
    "CreateAutomationRequest",
    "UpdateAutomationRequest",
    "AutomationResponse",
    "AutomationListResponse",
    "TestAutomationRequest",
    "TestAutomationResponse",
    "TriggerSchema",
    "StepSchema",
    "MessageTemplateSchema",
    "ButtonSchema",
    "CarouselElementSchema",
    # Contact schemas
    "ContactCreateRequest",
    "ContactUpdateRequest",
    "ContactResponse",
    "ContactListResponse",
    "ContactSearchRequest",
    "BulkCreateContactsRequest",
    "BulkCreateContactsResponse",
    "AddTagRequest",
    "RemoveTagRequest",
    "ContactExportRequest",
    "ContactImportRequest",
    "ContactImportResponse",
    # Message schemas
    "TextMessageSchema",
    "GenericTemplateSchema",
    "CarouselSchema",
    "ImageMessageSchema",
    "VideoMessageSchema",
    "FileMessageSchema",
    "CreateMessageTemplateRequest",
    "UpdateMessageTemplateRequest",
    "MessageTemplateResponse",
    "MessageTemplateListResponse",
    "PreviewMessageRequest",
    "PreviewMessageResponse",
    # Analytics schemas
    "DailyAnalyticsResponse",
    "DateRangeAnalyticsResponse",
    "PerformanceMetricsResponse",
    "EngagementMetricsResponse",
    "ErrorBreakdownResponse",
    "AnalyticsDashboardResponse",
    "ExportAnalyticsRequest",
    "AutomationAnalyticsResponse",
    "StepAnalyticsResponse",
]
